# Generated by Django 5.1.2 on 2024-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('description', models.TextField(max_length=50000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
