# Generated by Django 5.1.2 on 2024-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofie',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofie',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofie',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofie',
            name='marital_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofie',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
