# Generated by Django 5.1.2 on 2024-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_delete_userprofie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default='default_images/user.png', upload_to='profile_images/'),
        ),
    ]
